import JSZip from "jszip";
import type { Portfolio } from "@/lib/types";
import type { EditorTheme } from "@/lib/theme";
import { css } from "./html";
import { slugify } from "./download";

/**
 * Build a clean, self-contained Next.js 15 project that renders the portfolio
 * from a bundled data file, styled with the same design as the HTML export.
 */
export async function buildNextjsZip(
  p: Portfolio,
  theme: EditorTheme,
): Promise<Blob> {
  const zip = new JSZip();
  const name = slugify(p.hero.name);
  const title = p.meta.title || `${p.hero.name} — ${p.hero.role}`;
  const desc = p.meta.description || p.hero.intro || `${p.hero.name}'s portfolio.`;

  zip.file("package.json", PACKAGE_JSON(name));
  zip.file("next.config.ts", NEXT_CONFIG);
  zip.file("tsconfig.json", TSCONFIG);
  zip.file(".gitignore", GITIGNORE);
  zip.file("README.md", README(p.hero.name));
  zip.file("app/globals.css", css(theme));
  zip.file("app/layout.tsx", LAYOUT(title, desc));
  zip.file("app/page.tsx", PAGE);
  zip.file("lib/types.ts", TYPES);
  zip.file(
    "lib/portfolio-data.ts",
    `import type { Portfolio } from "./types";\n\nexport const portfolio: Portfolio = ${JSON.stringify(p, null, 2)};\n`,
  );
  zip.file("components/portfolio.tsx", COMPONENT);

  return zip.generateAsync({ type: "blob" });
}

const PACKAGE_JSON = (name: string) =>
  JSON.stringify(
    {
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "15.5.20",
        react: "19.1.0",
        "react-dom": "19.1.0",
      },
      devDependencies: {
        typescript: "^5",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
      },
    },
    null,
    2,
  );

const NEXT_CONFIG = `import type { NextConfig } from "next";
const nextConfig: NextConfig = {};
export default nextConfig;
`;

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  },
  null,
  2,
);

const GITIGNORE = `/node_modules\n/.next\n/out\n.env*\n.DS_Store\n`;

const README = (name: string) => `# ${name} — portfolio

Generated by [onepage](https://onepage.app). A single-page Next.js 15 portfolio.

## Develop

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:3000. Edit your content in \`lib/portfolio-data.ts\`.

## Deploy

Push to GitHub and import the repo at [vercel.com/new](https://vercel.com/new),
or run \`npx vercel\`.
`;

const LAYOUT = (title: string, desc: string) => `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(title)},
  description: ${JSON.stringify(desc)},
  openGraph: { title: ${JSON.stringify(title)}, description: ${JSON.stringify(desc)}, type: "website" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Instrument+Serif:ital@0;1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
`;

const PAGE = `import { PortfolioSite } from "@/components/portfolio";

export default function Home() {
  return <PortfolioSite />;
}
`;

const TYPES = `export interface SocialLinks {
  email?: string; phone?: string; linkedin?: string; github?: string;
  website?: string; twitter?: string; resume?: string;
}
export interface Hero { name: string; role: string; location?: string; intro?: string; links: SocialLinks; }
export interface Education { id: string; institution: string; degree: string; duration?: string; cgpa?: string; location?: string; coursework?: string[]; }
export interface Experience { id: string; company: string; role: string; duration?: string; location?: string; achievements: string[]; tech?: string[]; }
export interface Project { id: string; name: string; description: string; tech?: string[]; github?: string; demo?: string; image?: string; }
export interface SkillGroup { category: string; items: string[]; }
export type AchievementKind = "hackathon" | "award" | "publication" | "certificate" | "other";
export interface Achievement { id: string; title: string; description?: string; kind: AchievementKind; date?: string; link?: string; }
export interface PortfolioMeta { title?: string; description?: string; palette?: string[]; }
export type SectionId = "hero" | "education" | "experience" | "projects" | "skills" | "achievements" | "contact" | "thankyou";
export interface Portfolio {
  hero: Hero; education: Education[]; experience: Experience[]; projects: Project[];
  skills: SkillGroup[]; achievements: Achievement[]; meta: PortfolioMeta; sectionOrder: SectionId[];
}
`;

// The rendering component. Kept dependency-free and class-based to match globals.css.
const COMPONENT = String.raw`"use client";

import { useEffect } from "react";
import { portfolio } from "@/lib/portfolio-data";
import type { Portfolio } from "@/lib/types";

function useReveal() {
  useEffect(() => {
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            e.target.classList.add("in");
            io.unobserve(e.target);
          }
        });
      },
      { threshold: 0.15 },
    );
    document.querySelectorAll(".reveal").forEach((el) => io.observe(el));
    return () => io.disconnect();
  }, []);
}

function Links({ p }: { p: Portfolio }) {
  const l = p.hero.links;
  const items: { href: string; label: string }[] = [];
  if (l.email) items.push({ href: "mailto:" + l.email, label: "Email" });
  if (l.phone) items.push({ href: "tel:" + l.phone, label: "Phone" });
  if (l.linkedin) items.push({ href: l.linkedin, label: "LinkedIn" });
  if (l.github) items.push({ href: l.github, label: "GitHub" });
  if (l.website) items.push({ href: l.website, label: "Website" });
  if (!items.length) return null;
  return (
    <div className="links">
      {items.map((it) => (
        <a key={it.label} className="icon glass" href={it.href} target="_blank" rel="noreferrer" title={it.label}>
          {it.label[0]}
        </a>
      ))}
    </div>
  );
}

function Heading({ eyebrow, title }: { eyebrow: string; title: string }) {
  return (
    <div className="heading-block reveal">
      <p className="eyebrow accent">{eyebrow}</p>
      <h2 className="headline">{title}</h2>
    </div>
  );
}

export function PortfolioSite() {
  useReveal();
  const p = portfolio;
  const rec = p as unknown as Record<string, unknown[]>;
  const has = (id: string) =>
    ["hero", "contact", "thankyou"].includes(id) ||
    (Array.isArray(rec[id]) && rec[id].length > 0);
  const order = p.sectionOrder.filter(has);

  return (
    <>
      <div className="bg" />
      {order.map((id) => {
        if (id === "hero") {
          const meta = [p.hero.role, p.hero.location].filter(Boolean).join("  ·  ");
          return (
            <section id="hero" className="center" key={id}>
              {meta && <p className="eyebrow">{meta}</p>}
              <h1 className="display" style={{ marginTop: "1.5rem" }}>{p.hero.name}</h1>
              {p.hero.intro && <p className="lead" style={{ margin: "2rem auto 0" }}>{p.hero.intro}</p>}
              <Links p={p} />
            </section>
          );
        }
        if (id === "education")
          return (
            <section id="education" className="top" key={id}>
              <Heading eyebrow="Education" title="Education" />
              <div className="tl">
                {p.education.map((e) => (
                  <div className="tl-item reveal" key={e.id}>
                    <span className="node">◦</span>
                    <div className="glass card">
                      {e.duration && <p className="when">{e.duration}</p>}
                      <h3>{e.institution}</h3>
                      {e.degree && <p className="sub">{e.degree}</p>}
                      <div className="tags">
                        {e.cgpa && <span className="tag">CGPA {e.cgpa}</span>}
                        {(e.coursework ?? []).map((c) => <span className="tag" key={c}>{c}</span>)}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          );
        if (id === "experience")
          return (
            <section id="experience" className="top" key={id}>
              <Heading eyebrow="Experience" title="Experience" />
              <div className="tl">
                {p.experience.map((x) => (
                  <div className="tl-item reveal" key={x.id}>
                    <span className="node dot" />
                    <div className="glass card">
                      <div style={{ display: "flex", justifyContent: "space-between", gap: "1rem", flexWrap: "wrap" }}>
                        <div>
                          <h3>{x.role || x.company}</h3>
                          {x.role && <p className="sub">{x.company}{x.location ? " · " + x.location : ""}</p>}
                        </div>
                        {x.duration && <p className="when">{x.duration}</p>}
                      </div>
                      {x.achievements.length > 0 && (
                        <ul className="bullets">
                          {x.achievements.map((a, i) => <li key={i}><span>{a}</span></li>)}
                        </ul>
                      )}
                      {x.tech && x.tech.length > 0 && (
                        <div className="tags">{x.tech.map((t) => <span className="tag" key={t}>{t}</span>)}</div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </section>
          );
        if (id === "projects")
          return (
            <section id="projects" className="top" key={id}>
              <Heading eyebrow="Selected work" title="Projects" />
              <div className={"grid " + (p.projects.length > 1 ? "two" : "")}>
                {p.projects.map((pr) => (
                  <div className="glass card reveal" style={{ padding: 0, overflow: "hidden" }} key={pr.id}>
                    <div className="proj-img"><span>{pr.name.charAt(0).toUpperCase()}</span></div>
                    <div style={{ padding: "1.5rem" }}>
                      <h3 style={{ fontSize: "1.15rem" }}>{pr.name}</h3>
                      {pr.description && <p className="sub" style={{ marginTop: ".5rem" }}>{pr.description}</p>}
                      <div className="tags">{(pr.tech ?? []).map((t) => <span className="tag" key={t}>{t}</span>)}</div>
                      <div className="tags">
                        {pr.github && <a className="tag" href={pr.github} target="_blank" rel="noreferrer">GitHub ↗</a>}
                        {pr.demo && <a className="tag" href={pr.demo} target="_blank" rel="noreferrer">Live demo ↗</a>}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </section>
          );
        if (id === "skills")
          return (
            <section id="skills" className="top" key={id}>
              <Heading eyebrow="Capabilities" title="Skills" />
              <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
                {p.skills.map((g) => (
                  <div className="skill-row reveal" key={g.category}>
                    <p className="skill-cat">{g.category}</p>
                    <div className="tags" style={{ marginTop: 0 }}>
                      {g.items.map((it) => <span className="tag" key={it}>{it}</span>)}
                    </div>
                  </div>
                ))}
              </div>
            </section>
          );
        if (id === "achievements")
          return (
            <section id="achievements" className="top" key={id}>
              <Heading eyebrow="Recognition" title="Achievements" />
              <div className={"grid " + (p.achievements.length > 1 ? "two" : "")}>
                {p.achievements.map((a) => (
                  <div className="glass card reveal" key={a.id}>
                    <h3 style={{ fontSize: "1.05rem" }}>{a.title}</h3>
                    <p className="when" style={{ marginTop: ".4rem" }}>{a.kind}{a.date ? " · " + a.date : ""}</p>
                    {a.description && <p className="sub" style={{ marginTop: ".5rem" }}>{a.description}</p>}
                  </div>
                ))}
              </div>
            </section>
          );
        if (id === "contact")
          return (
            <section id="contact" key={id}>
              <div className="contact-grid">
                <div>
                  <Heading eyebrow="Get in touch" title="Let's build something." />
                  <p className="lead" style={{ marginTop: 0 }}>Have a role, a project, or just want to say hello? My inbox is always open.</p>
                  {p.hero.links.email && <a className="contact-line" href={"mailto:" + p.hero.links.email}>{p.hero.links.email}</a>}
                  {p.hero.links.phone && <a className="contact-line" href={"tel:" + p.hero.links.phone}>{p.hero.links.phone}</a>}
                  <Links p={p} />
                </div>
                <form
                  className="glass"
                  style={{ padding: "2rem" }}
                  {...(p.hero.links.email ? { action: "mailto:" + p.hero.links.email, method: "post", encType: "text/plain" } : {})}
                >
                  <input className="field" name="name" placeholder="Your name" required />
                  <input className="field" name="email" type="email" placeholder="Your email" required />
                  <textarea className="field" name="message" rows={4} placeholder="Your message" required />
                  <button className="btn" type="submit">Send message</button>
                </form>
              </div>
            </section>
          );
        // thankyou
        return (
          <section id="thankyou" className="center" key={id}>
            <p className="eyebrow">That&apos;s a wrap</p>
            <h2 className="display" style={{ marginTop: "1.5rem" }}>Thank<span className="grad"> you</span>.</h2>
            <p className="lead" style={{ margin: "2rem auto 0" }}>Thanks for scrolling all the way through.</p>
            <p className="footer">© {new Date().getFullYear()} {p.hero.name} · Crafted with onepage</p>
          </section>
        );
      })}
    </>
  );
}
`;
